### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by Ygarr** [WinterLicht/Chaos-Projectile#17]
 master  …   Chaos-Projectile  src    05:26:12 python game.py
  File "/.../Chaos-Projectile/src/game.py", line 59
    print "os: Windows Vista or newer"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("os: Windows Vista or newer")?

python setup.py build                                                        1 
Traceback (most recent call last):
  File "/.../Chaos-Projectile/src/setup.py", line 7, in <module>
    from cx_Freeze import setup, Executable
ModuleNotFoundError: No module named 'cx_Freeze'

**Comment by bitcraft** [comment]
the source code has not been updated to use python 3.  you will need to try again with python 2.7.
